
function [Domain, mapping, InterpFace, outputFinal] = runLoftedSurfaceInterpolation(opts)
% RUNLOFTEDSURFACEINTERPOLATION Main entry point for lofted-surface mapping and interpolation.
% Author: Joey.Chow
%
% Optional input:
%   opts.nelx, opts.nely, opts.nelz       - Macro-element numbers.
%   opts.microSize                       - Micro-cell sampling size.
%   opts.numofTesserae                   - Number of input sectional STLs.
%   opts.stlBaseName                     - Prefix of sectional STL files.
%   opts.numParamX, opts.numParamY       - Shared surface sampling resolution.
%   opts.numInterpLayers                 - Number of reconstructed intermediate layers.
%   opts.doReconstruction                - Whether to run Beltrami reconstruction.
%   opts.doReviewerJacobianReport        - Whether to export the Jacobian report.
%   opts.showFigures                     - Whether figures are visible during execution.
%   opts.saveReviewerFiles               - Whether to save .fig/.csv/.txt validation files.
%
% Output:
%   Domain      - Design-domain structure. Domain.X/Y/Zcood_MA contain the
%                 physical macro mesh used for Jacobian validation.
%   mapping     - Conformal parameterization for each tessera.
%   InterpFace  - Interpolated surface data on a shared triangulation.
%   outputFinal - Reconstructed intermediate surfaces; empty if reconstruction is disabled.

if nargin < 1 || isempty(opts)
    opts = struct();
end

rootDir = fileparts(mfilename('fullpath'));
addpath(rootDir);
addpath(genpath(fullfile(rootDir, 'DomainMaterialDef')));
addpath(genpath(fullfile(rootDir, 'modelProcess')));
addpath(genpath(fullfile(rootDir, 'confmap')));
addpath(genpath(fullfile(rootDir, 'geometry')));
addpath(genpath(fullfile(rootDir, 'stlTools')));
addpath(genpath(fullfile(rootDir, 'area')));
addpath(genpath(fullfile(rootDir, 'initialModel')));
addpath(genpath(fullfile(rootDir, 'validation')));

showFigures = getOption(opts, 'showFigures', true);
if ~showFigures
    oldFigVisible = get(0, 'DefaultFigureVisible');
    set(0, 'DefaultFigureVisible', 'off');
    cleanupObj = onCleanup(@() set(0, 'DefaultFigureVisible', oldFigVisible)); %#ok<NASGU>
end

%% Optimization / geometry parameters
% The default macro mesh is set to 16 x 10 x 20 = 3200 elements, matching
% the first numerical example in the revised manuscript and the reviewer request.
nelx = getOption(opts, 'nelx', 16);
nely = getOption(opts, 'nely', 10);
nelz = getOption(opts, 'nelz', 20);

microSize = getOption(opts, 'microSize', 31);
numofTesserae = getOption(opts, 'numofTesserae', 5);
stlBaseName = getOption(opts, 'stlBaseName', 'TranS');

doReconstruction = getOption(opts, 'doReconstruction', true);
doReviewerJacobianReport = getOption(opts, 'doReviewerJacobianReport', false);
saveReviewerFiles = getOption(opts, 'saveReviewerFiles', false);
plotNormalizedReviewerHistogram = getOption(opts, 'plotNormalizedReviewerHistogram', true);
makeReviewerContour = getOption(opts, 'makeReviewerContour', false);

%% Domain initialization
Domain = initializeDomain(nelx, nely, nelz, microSize, 1);
Domain.mapping = cell(nelz + 1, 1);

%% Surface processing
mapping = cell(numofTesserae, 1);
[Domain, mapping] = processLoftedSurfaces(Domain, mapping, stlBaseName, numofTesserae);

%% Direct reviewer validation on the physical macro mesh
% This validates the actual physical hexahedral macro-elements generated by
% Domain.Xcood_MA, Domain.Ycood_MA, and Domain.Zcood_MA. It is independent
% of the visualized triangular intermediate surfaces.
if doReviewerJacobianReport
    resultDir = fullfile(rootDir, 'results', 'reviewer_jacobian');
    if ~exist(resultDir, 'dir')
        mkdir(resultDir);
    end
    Domain.jacobianReport = plotJacobianDeterminantReport(Domain, resultDir, ...
        'caseName', sprintf('translation_%dx%dx%d', nelx, nely, nelz), ...
        'showFigures', showFigures, ...
        'plotNormalizedHistogram', plotNormalizedReviewerHistogram, ...
        'makeContour', makeReviewerContour, ...
        'saveFiles', saveReviewerFiles);
    if saveReviewerFiles
        save(fullfile(resultDir, 'Domain_with_jacobian_report.mat'), 'Domain', 'mapping');
    end
end

%% Optional reconstruction of intermediate surfaces from Beltrami data
InterpFace = struct();
outputFinal = [];
if ~doReconstruction
    return;
end

numX = getOption(opts, 'numParamX', 50);
numY = getOption(opts, 'numParamY', 60);
basicXX = linspace(0, 1, numX);

InterpFace.Point = cell(numofTesserae, 1);

figure;
for i = 1:numofTesserae
    basicYY = linspace(0, Domain.H(i), numY);
    [basicGrid_X, basicGrid_Y] = meshgrid(basicXX, basicYY);

    DT_basic = delaunayTriangulation(reshape(basicGrid_X, [], 1), reshape(basicGrid_Y, [], 1));
    InterpFace.faces = DT_basic.ConnectivityList;

    F1 = scatteredInterpolant(mapping{i}, Domain.vertices{i}(:, 1), 'natural');
    F2 = scatteredInterpolant(mapping{i}, Domain.vertices{i}(:, 2), 'natural');
    F3 = scatteredInterpolant(mapping{i}, Domain.vertices{i}(:, 3), 'natural');

    InterpFace.Point{i}(:, 1) = reshape(F1(basicGrid_X, basicGrid_Y), [], 1);
    InterpFace.Point{i}(:, 2) = reshape(F2(basicGrid_X, basicGrid_Y), [], 1);
    InterpFace.Point{i}(:, 3) = reshape(F3(basicGrid_X, basicGrid_Y), [], 1);

    plotTriMesh(InterpFace.Point{i}, InterpFace.faces);
    hold on;
end
hold off;

%% Compute Beltrami coefficient and perform local spline interpolation
numInterpLayers = getOption(opts, 'numInterpLayers', nelz + 1);
H_i = linspace(Domain.Zcood_MA(1, 1, 1), Domain.Zcood_MA(1, 1, end), numInterpLayers);

RefNUM = ones(length(H_i), 1);
InterpFace.mu_t = cell(length(H_i), 1);
InterpFace.Beltrami_coeff = cell(numofTesserae, 1);
InterpFace.BeltramiInterpMethod = 'Local cubic Hermite spline on stretch quotient and angle';

for i = 1:numofTesserae
    InterpFace.Beltrami_coeff{i} = computeBeltramiCoefficient(InterpFace.Point{1}, InterpFace.faces, InterpFace.Point{i});
end

muSamples = zeros(size(InterpFace.Beltrami_coeff{1}, 1), numofTesserae);
for i = 1:numofTesserae
    muSamples(:, i) = InterpFace.Beltrami_coeff{i};
end

muInterp = interpolateBeltramiLocalSpline(Domain.faceHeight, muSamples, H_i);
for i = 1:length(H_i)
    RefNUM(i) = 1;
    InterpFace.mu_t{i} = muInterp(:, i);
end

%% Interpolate the four boundaries
F = freeBoundary(DT_basic);
BoundaryIndex = F(:, 1);

TesseraeBoundaryX = zeros(numofTesserae, length(BoundaryIndex));
TesseraeBoundaryY = zeros(numofTesserae, length(BoundaryIndex));
TesseraeBoundaryZ = zeros(numofTesserae, length(BoundaryIndex));

for i = 1:numofTesserae
    TesseraeBoundaryX(i, :) = InterpFace.Point{i}(BoundaryIndex, 1);
    TesseraeBoundaryY(i, :) = InterpFace.Point{i}(BoundaryIndex, 2);
    TesseraeBoundaryZ(i, :) = InterpFace.Point{i}(BoundaryIndex, 3);
end

Corner = struct();
Corner.boundaryX = zeros(length(H_i), length(BoundaryIndex));
Corner.boundaryY = zeros(length(H_i), length(BoundaryIndex));
Corner.boundaryZ = zeros(length(H_i), length(BoundaryIndex));

for i = 1:length(BoundaryIndex)
    Corner.boundaryX(:, i) = makima(Domain.faceHeight, TesseraeBoundaryX(:, i), H_i);
    Corner.boundaryY(:, i) = makima(Domain.faceHeight, TesseraeBoundaryY(:, i), H_i);
    Corner.boundaryZ(:, i) = makima(Domain.faceHeight, TesseraeBoundaryZ(:, i), H_i);
end
Corner.BoundaryIndex = BoundaryIndex;

save(fullfile(rootDir, 'InterpFace.mat'), 'InterpFace', 'H_i', 'RefNUM', 'Corner', 'Domain');

%% Reconstruct surfaces from the Beltrami coefficient
outputFinal = reconstructInterpolatedSurfaces(InterpFace, H_i, RefNUM, Corner);
save(fullfile(rootDir, 'outputFinal2.mat'), 'outputFinal');

%% Export figures
resultDir = fullfile(rootDir, 'results');
if ~exist(resultDir, 'dir')
    mkdir(resultDir);
end

for i = 1:length(H_i)
    fig = figure('Visible', 'off');
    plotTriMesh(outputFinal(:, :, i), InterpFace.faces);
    hold on;
    plot3(outputFinal(Corner.BoundaryIndex, 1, i), ...
          outputFinal(Corner.BoundaryIndex, 2, i), ...
          outputFinal(Corner.BoundaryIndex, 3, i), ...
          'LineWidth', 2, 'Color', 'b', 'LineStyle', '--');
    plot3(outputFinal(Corner.BoundaryIndex([1, end]), 1, i), ...
          outputFinal(Corner.BoundaryIndex([1, end]), 2, i), ...
          outputFinal(Corner.BoundaryIndex([1, end]), 3, i), ...
          'LineWidth', 2, 'Color', 'b', 'LineStyle', '--');
    view(0, 90);
    axis equal off;
    saveas(fig, fullfile(resultDir, sprintf('interpFace100%d.jpg', i)), 'jpg');
    close(fig);
end

figure;
for i = 1:length(H_i)
    plotTriMesh([outputFinal(:, 1, i), outputFinal(:, 2, i), outputFinal(:, 3, i) + H_i(i)], InterpFace.faces);
    hold on;
    view(0, 90);
    axis equal off;
end
hold off;

end

function value = getOption(opts, fieldName, defaultValue)
%GETOPTION Read an option from a struct with a default fallback.
if isstruct(opts) && isfield(opts, fieldName) && ~isempty(opts.(fieldName))
    value = opts.(fieldName);
else
    value = defaultValue;
end
end
